language: python
sudo: false
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
  - cd native
  - python setup.py build
  - python setup.py install
  - cd ..
script: python setup.py nosetests --with-coverage --cover-package=thrift_tools
after_success:
  coveralls
